name: style check for linux driver
on:
  push:
    paths:
      - driver/linux/**
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: style check
        working-directory: ./driver/linux
        run : make style
