name: test build linux driver

on:
  push:
    paths:
      - driver/linux/**
      - .github/workflows/linux-driver-test-build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build
        working-directory: ./driver/linux
        run : make build
